### PR TITLE
These corrections also translate multi-year

### PR DESCRIPTION
**Pull request by ValentinChernyshov**
This is the solution for bug number 133 : https://github.com/SaturnTeam/saturn-datepicker/issues/133

### CODE REVIEW

**Comment by SaturnTeam** [comment]
I'll check on weekends

**Comment by ValentinChernyshov** [comment]
> I'll check on weekends

Thank you. 

P.s. Easter egg 
image

**Comment by ValentinChernyshov** [comment]
@SaturnTeam , can you please build the project with new changes on npm? The last update was three months ago.

**Comment by SaturnTeam** [comment]
@ValentinChernyshov I tried to build Saturday project. And I failed. Ivy made things harder. I'll continue building today

**Comment by ValentinChernyshov** [comment]
> @ValentinChernyshov I tried to build Saturday project. And I failed. Ivy made things harder. I'll continue building today

@SaturnTeam , hi! How are you doing with the release of the new version on npmjs?)

**Comment by ValentinChernyshov** [comment]
@SaturnTeam ,  do not give up trying to build a project!
image

**Comment by SaturnTeam** [comment]
@ValentinChernyshov I've tried a lot. I'm going to try again. Where was bug in node or something nearby.

**Comment by ValentinChernyshov** [comment]
@SaturnTeam , hey, hello, when will version 8.0.6 already be?)

**Pull request merged**
