### PR TITLE
Add rangeHoverEffect parameter to sat-datepicker

### PR DESCRIPTION
**Pull request by LeParadoxHD**
This change is for those users who prefer to not have the mouseover effect when rangeMode is enabled.

### CODE REVIEW

**Comment by SaturnTeam** [comment]
This seems ok. I'll merge it at home this week. If I forget - ping me

**Comment by SaturnTeam** [comment]
@LeParadoxHD Please add an example to the examples, and I'll merge it

**Comment by SaturnTeam** [comment]
and to the readme

**Comment by LeParadoxHD** [comment]
@SaturnTeam Added documentation on examples and readmes

**Comment by LeParadoxHD** [comment]
@SaturnTeam When will 8.0.2 be available from the npm repository?

**Comment by SaturnTeam** [comment]
@LeParadoxHD  Sorry, I forgot to change version. Now it's ok

**Pull request merged**
