### PR TITLE
fix: remove unnecessary moduleId: module.id

### PR DESCRIPTION
**Pull request by ThibaudAV**
I have run the application everything seems to work correctly. The build of the lib works too

### CODE REVIEW

**Comment by WillGeller** [comment]
Thanks for doing this fix! Is it available on the NPM release at the moment or will it be going into the next patch @ https://www.npmjs.com/package/saturn-datepicker?activeTab=versions soon?

**Comment by WillGeller** [comment]
Is it availble on the NPM release at the moment?

**Comment by SaturnTeam** [comment]
No. Because I have to compile the lib before publish. And I cannot compile due to using old ng-packgr.

**Comment by WillGeller** [comment]
I see, is that going to postpone releasing new updates to this library
then? This issue is a blocker on my team being able to use it, but we are
in Angular 8 so can't use the official version and would like to use yours.
Let me know if I can help in anyway.

**Comment by SaturnTeam** [comment]
Anyway, next version would be for Angular 10, so I recommend to copy code from repository or upgrade to Angular 10

**Pull request merged**
